spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt-service
    username: user
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: jwt-service

eureka:
  instance:
    prefer-ip-address:true
  client:
    service-url:
      defaultZone : http://eureka:password@localhost:8761/eureka

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 8900